site_name: Django ReBAC
site_url: https://ormuslabs.github.io/django-rebac/
site_description: A declarative, strictly-typed ReBAC framework for Django.

theme:
  name: material
  palette:
    primary: indigo

nav:
  - Home: index.md
