# Generated by Django 5.2.13 on 2026-08-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rebacsyncoutbox',
            options={'ordering': ('created_at', 'id'), 'verbose_name': 'ReBac Sync Task', 'verbose_name_plural': 'ReBac Sync Tasks'},
        ),
    ]
